### ISSUE TITLE
[BUG] SteamOverlay - random joining + other thing + feature at the end

### ISSUE THREAD

**Issue by borrou** [pypy-vrc/VRCX#145]
Hello !
I don't know what's happening in this release, but there's multiple bug... I think downgrade until the release is fix :/ ...
Is it really useful to add "notification everywhere" ???

at first, I don't see people who joining the room where I am in the overlay...
and when I edit some element in the VRCX setting, It seem not work, so, yeah...

Second, I see some issue about "Notification" problem without any value (I saw, it's fixed for the next update)

Third : sometimes, I appear in Japan Shrine ?!?!? same if I don't join Japan Shrine world since multiple day...

Fourth (feature) : is it possible to add ourself a limit of the log ? because I can't see what's happened 1/2w ago, log file is really short...

and also, thank you for your hard work :)
I don't have this level... so, I can't help you than create issue and add what's happening, sorry :/

**Comment by Natsumi-sama** [comment]
1, 2. https://github.com/pypy-vrc/VRCX/issues/142#issuecomment-772611396 either wait for next update or build it yourself.
3. This is a known bug that only occurs while the game is starting because you aren't in any world yet so it shows your last world instead, I might fix it at some point but it's pretty harmless.
4. Yea this should be possible, but there is a good reason for this limit it takes a very long time to load large amounts of logs. https://github.com/pypy-vrc/VRCX/issues/133

**Comment by borrou** [comment]
sorry for my late answer,
3. that's not the thing... I'm always in Japan Shrine, same if I'm connected...he don't show my real location.
4. I looking for an alternative to your system, and now I think I have an idea, I'll give you more information later

**Comment by Natsumi-sama** [comment]
ah 3. is this again https://github.com/pypy-vrc/VRCX/issues/142 wait for release.
