### ISSUE TITLE
Block: log and options

### ISSUE THREAD

**Issue by Crow-tm** [pypy-vrc/VRCX#150]
Log: Unblocking deletes the log of having been blocked.

Tested this today with a friend and there's no log of him having blocked me even though I had gotten a notification about the initial block. 

Options: Also sometimes this happens when clicking on user options, all of it is red, does that mean they blocked me? 
Also tested with a friend who blocked me for 5 minutes, but.. Not every time would it be the same, however when sending request to them it would be denied. Notification rejected
![image](https://user-images.githubusercontent.com/72923709/107152445-357f9100-6968-11eb-973a-bee888d04123.png)

Another question: Is it possible for it to show someone online even though they'd left the game about 30 minutes earlier? 
When sending invites to them, these invites do not appear in outgoing invites, so I suppose they weren't delivered, however wondering about the block interaction...

**Comment by Natsumi-sama** [comment]
The moderation log just displays what's stored in VRChat's servers, would have to completely change how it works in order to achieve that.

That seems to be a bug that occurs when your game is running and you have a user dialog box open while a moderation log refresh is happening in the background, a quick fix would be to just reopen the user dialog box, I wasn't aware of this one so I will look into it at some point.
