### ISSUE TITLE
Notifications not working anymore. [at least for me they aren't]

### ISSUE THREAD

**Issue by AsrielDreemur7** [pypy-vrc/VRCX#236]
Im not entirely sure if this is just a me thing or not, but i still do want to point it out.. the very first update that the notifications option in VRCX came out, it worked flawlessly and during that time my anti-virus didnt ever try blocking vrcx, but the next following updates and up to right now,  if i were to try to use the notifications, i dont get them, none of them. Now it could just be a setting i set on my PC by accident, but i personally did try looking everywhere for something like that, but i had no luck.. and not to mention now the anti-virus does try to think its a virus when its clearly not. "im not trying to point out 2 issues, im just pointing out that.. the period when the notifcations stopped was around the time the anti-virus started being dumb and saying it was a virus, when i know it isn't."

Anyways.. if there is anyway for me to know, why exactly aren't they working for me.. i  have them set up them like in the screenshot below
![image](https://user-images.githubusercontent.com/83406421/124300071-26be9400-db2c-11eb-94f6-6df4959798ec.png)
![image](https://user-images.githubusercontent.com/83406421/124300123-363ddd00-db2c-11eb-8f73-f91cb6b97d1d.png)

yet i get absolutly no notifcations from VRCX,  but anywho to wrap this up,  if its a setting i messed up then ill be happy to know what i messed up since i do like getting the notifications and for a while i have dealt with them just not working anymore but now i feel like its worth to ask.

**Comment by Natsumi-sama** [comment]
If you don't have XS Overlay try disable that option, also are you having problems with VR notifications or desktop ones?

**Comment by AsrielDreemur7** [comment]
its the desktop, i thought by turning on that XS overlay it would get the notifications to work again, but it never did anything.. so... its really the desktop ones, Im not sure about VR since i dont have a VR, so as of right now, i only know im having issues with the desktop notifications

**Comment by Natsumi-sama** [comment]
Hmm alright make sure [notifications](https://support.microsoft.com/en-us/windows/change-notification-settings-in-windows-10-ddcbbcd4-0a02-f6e4-fe14-6766d850f294) are enabled in windows settings because VRCX uses it to display notifications.

**Comment by AsrielDreemur7** [comment]
in the settings app, i dont see vrcx showing up, so maybe i did something wrong

**Comment by Natsumi-sama** [comment]
It's not there for me either and I don't think you have done anything wrong, are the notifications visible in the action center? maybe you have "Focus Assist" enabled?

**Comment by AsrielDreemur7** [comment]
i dont exactly have focus assist enabled, and i do see other notifications from other apps in the action center, but nothing from vrcx.

**Comment by AsrielDreemur7** [comment]
i see theres a new update.. ill check if it works now in this newer one

**Comment by AsrielDreemur7** [comment]
Ok so when i logged on to vrcx using a different user account on my windows laptop, i got notifications.. but when i switched back to my original account and logged on to vrcx on my normal user account.. i didn't get any notifications.. so i think its something on my end.. so ill continue to look into what might be causing it.

**Comment by SubtleHeat** [comment]
I've triggered this same issue. I right-clicked a notification and clicked "Mute all notifications" as a temporary measure to stop some spam. After doing that, I've been unable to get them back.   

The registry key 
`Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\VRCX\Enabled` keeps getting written back to 0. I've cleared every reference I can from the registry but it won't come back.  

VRCX doesn't appear in the list of applications that are allowed/blocked from sending toasts in Windows.

**Comment by SubtleHeat** [comment]
Did some research and came to a solution. Windows is being Windows here. 

ToastNotificationManager.CreateToastNotifier("VRCX") is returning DisabledForApplication (as expected since I clicked the button in the notification to mute all notifications from the application)  

Turns out, the docs are pretty explicit in saying that there needs to be a shortcut with an AppUserModelID for toasts to work for Win32 apps.  
https://docs.microsoft.com/en-us/windows/win32/shell/quickstart-sending-desktop-toast
> You must include the AppUserModelID of your app's shortcut on the Start screen each time that you call CreateToastNotifier. If you fail to do this, your toast will not be displayed.  

Obviously, this isn't 100% true. The toasts display, but the toast notifier doesn't register in a useful way (e.g. if you disable them, you can't re-enable them. You also can't customize how they show in the action center)

Using this person's library, I was able to manually create the shortcut which added VRCX to the list on the "Notifications & Actions" page and I was able to re-enable it.
https://emoacht.wordpress.com/2012/11/14/csharp-appusermodelid/  
I don't have the time to submit a PR right now. This person's code is MIT.  

Here's the official docs with the CPP COM garbage for reference.
https://docs.microsoft.com/en-us/windows/win32/shell/enable-desktop-toast-with-appusermodelid
