### ISSUE TITLE
[Feature Request] Auto Download Avatars

### ISSUE THREAD

**Issue by ArinCollie** [pypy-vrc/VRCX#243]
This may be a bit of a niche request, but it would still be really helpful nonetheless. I'm on Satellite internet and have been using the auto-download world feature to cache as many worlds my friends go to as I can because the download speeds are terribly slow sometimes.

It's been super useful, but I still run into the issue of needing to download every avatar or avatar update any of my friends have, which causes me to lag incredibly hard and often time-out. I've had to keep a lot of friends' avatars hidden just to be able to talk to them, or risk timing-out just trying to download them.

Another friend of mine has a pretty slow laptop. He can run the game mostly fine, but when he joins a world with a lot of new avatars, it slows him down considerably, to the point where the frames are low enough he can't see or speak until they're all downloaded. This feature would only help get all his friends downloaded, but it would at least cut that down some.

Unlike the worlds, you can always see what avatar anyone is using at any given time, whether they're in a private world or not. It would be very useful if we could have an option to have VRCX download those as well. I figure some people are in a similar situation to either of us, and I'd hope it wouldn't be too difficult to pull off.

**Comment by Murkur** [comment]
"Unlike the worlds, you can always see what avatar anyone is using at any given time, whether they're in a private world or not." sorry but that is incorrect your able to see the avatar a person is in because we check the Thumbnail URL which is always exposed to the end user the thumbnail provides the name of the avatar its upload date the uploader and course the image problem is this doesn't show the avatars assetURL "the avatars actual unity File the game loads" and this will never be public or accessible to anyone besides the creator outside the game client so this feature will not be possible recent changes to the API also made removed the assetURL of public avatars aswell.

**Comment by Natsumi-sama** [comment]
Unfortunately Murkur is correct it would only be possible to cache your own uploaded avatars.

**Comment by ArinCollie** [comment]
Ahhh, unfortunate.
