### ISSUE TITLE
[Feature Suggestion - WEIRD] Remote database for storing records ? 

### ISSUE THREAD

**Issue by Miner28** [pypy-vrc/VRCX#293]
So as I mentioned this is a bit weird and unnecessary suggestion but would make my life easier… Any way to implement remote database connections like PostgreSQL for storing all the records instead of local DB ? Some kind of Master and user system for having 1 Master VRCX client running that would append to the database and then user client only reading ? I like to run my VRCX 24/7 on my home PC, but when I'm somewhere else, it's hard to access the records when I need to.

Not sure how hard would this be to implement, and not sure if others would find the use in this ?

**Comment by Natsumi-sama** [comment]
The front end is very tied to the back end so not easy at all https://github.com/pypy-vrc/VRCX/discussions/291 but I was planning (maybe someday) to have an option to use PostgreSQL instead of SQLite.

**Comment by Miner28** [comment]
Oh, nice. Well yea I was looking a bit myself at the code and would need lots of changed in the backend to allow different kinds of DBs to be used As for the front-end ? I understand roughly 0% of it. I am still quite a bit away from understanding the level of C# I'd need to help with VRCX, but once I do, I'd love to help.

**Comment by Natsumi-sama** [comment]
The database isn't shareable between instances of VRCX for so many reasons. The front end and back end is a single JS/HTML webpage it has zero backend separation meaning in order to have a second client it would need to be a new application that would read data from the main program and command the main program to do everything, i'm not going to write a second client. TLDR it would need a full rewrite to have proper support for multiple front ends.
