### ISSUE TITLE
Is it currently possible to have some sort of remote databases?

### ISSUE THREAD

**Issue by LunarstarPony** [pypy-vrc/VRCX#432]
So Instead of using my main PC I want to use one of my servers to log everything so I'm wondering if It's possible to have a remote databases rn?

**Comment by LunarstarPony** [comment]
Ah alright Because it would be nice to have a different system to handle the logging part but thanks eitherway! Hopefully it will be reconsider in the future < 3

**Comment by Fummowo** [comment]
I hope this feature is being considered in the rewrite :)
It would be very handy for data collection and scheduled visualizations like https://github.com/zkxs/vrcx-optimal-time

**Comment by trwnh** [comment]
> SQL support was planned at one point but it was decided against because not enough people would use it.

How can we show our support for this feature? It seems to have come up more than once:

- #1316 

It would be very nice to have database storage written to a proper SQL server instead of an SQLite database, as this would allow syncing the VRCX files to multiple computers without creating database conflicts. Currently, attempting to sync a VRCX folder creates a lot of noise because the database is constantly written to. (Syncing a VRCX folder is a desirable thing to do when VRChat is launched from more than one installation, such as in a dual-boot Windows and Linux setup, or with multiple computers. I already sync my VRChat "Pictures" folder, but syncing the activities themselves is very painful right now.)
