### ISSUE TITLE
[Feature request] Go to avatar page by ID

### ISSUE THREAD

**Issue by timduru** [pypy-vrc/VRCX#81]
Hello, 
with global search not being an option anymore,
it would be practical to be able to search / go to a public avatar directly given its ID
That way you can see and favorite/unfavorite it.

Currently the only way to do that is if you find the author who has uploaded it as a public avatar
then click on the avatar in the list, or if you have it already in your own avatar fav list.

It would be nice to be able to go directly to the avatar page if you paste the avatar ID in the avatar search tab.
In addition it would be also good to have the history of all the avatars you have visited previously to find them back quickly
(history stored locally)
Thanks

**Comment by Murkur** [comment]
this is incorrect from the MORE TAB (the settings cog) their is a 3 buttons called Direct Acess "World, Avatar, Usr" if you past in the corresponding ID in the box that pops up it will go o that avatar or world or user 
![image](https://user-images.githubusercontent.com/20288698/95010013-3720fd00-05f4-11eb-8c02-c2cdc67b92da.png) its been a feature since first release

**Comment by Murkur** [comment]
![AaWgH9l4DG](https://user-images.githubusercontent.com/20288698/95010076-93841c80-05f4-11eb-88ed-6ac0296bba64.gif)

**Comment by timduru** [comment]
perfect thanks :)
indeed direct id works from there, missed it  :)

**Comment by Murkur** [comment]
alright :) please close the thread if your finished 👍
